version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: docker
    directory: /e2e
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /hack/api-docs
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /hack/api-docs
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /e2e
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
