name: Dependency License Checks

on:
  pull_request:
    paths:
      - "go.mod"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: "Checkout Code"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@47ef11b1e1e3812e88dae436ccbd2d0cbd1adab0 # main
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}

      - name: "Run FOSSA Test"
        uses: fossas/fossa-action@47ef11b1e1e3812e88dae436ccbd2d0cbd1adab0 # main
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
          run-tests: true
